include:
  - board: seeeduino_xiao_ble
    shield: totem_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: totem_right rgbled_adapter

  - shield: settings_reset
    board: seeeduino_xiao_ble
  - board: nice_nano_v2
    shield: settings_reset
